// Central SEO metadata for every blog post. Server components under
// app/<slug>/page.tsx import from here so titles, descriptions, canonicals,
// and FAQ schema arrays all live in one place — no duplication between the
// useEffect-based client code and the metadata export.
//
// Rules applied while authoring this file:
// - Titles trimmed to <=60 characters (Google SERP truncation point).
// - Descriptions 150-160 characters, primary keyword in first 90 chars.
// - FAQ arrays mirror the accordion questions already visible on each page.

import type { FAQItem } from '@/lib/articleSchema';

export interface BlogSeo {
  slug: string;
  title: string;
  description: string;
  category: string;
  categorySlug: string; // the /blog?cat= value
  datePublished: string;
  dateModified: string;
  faqs?: FAQItem[];
  /** ISO UTC scheduled publish time. See lib/blogPosts.ts isPublished(). */
  publishAt?: string;
  /** SEO keyword metadata. Added as part of the keyword-density policy
   *  (1 primary, 2-5 secondary, long-tail as needed). Rendered into
   *  <meta name="keywords"> via generateKeywordsMeta() in articleSchema. */
  primaryKeyword?: string;
  secondaryKeywords?: string[];
  longTailKeywords?: string[];
}

export const BLOG_SEO: Record<string, BlogSeo> = {
  'pass-ats-resume-scanning': {
    slug: 'pass-ats-resume-scanning',
    title: 'How to Pass ATS Resume Scanning in 2026',
    description: 'Beat applicant tracking systems in 2026. 10 tactics, 7 ATS killers, PDF vs DOCX truth, top 5 systems, and free tools to test your resume.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'pass ATS resume scanning',
    secondaryKeywords: ["applicant tracking system","ATS resume tips","ATS optimisation"],
    longTailKeywords: ["how to pass ATS resume scanning 2026","what keywords ATS looks for","does ATS read PDF files","top 5 ATS systems used by Fortune 500","ATS score check","resume parsing errors to fix"],
    faqs: [
      { q: 'Does ATS read PDF?', a: 'Yes, modern ATS systems read selectable-text PDFs reliably. Scanned image PDFs fail because the text is locked inside an image.' },
      { q: 'How many keywords should I include?', a: 'Aim for 60 to 80 percent match on the hard skills and tools listed in the job description. Do not keyword-stuff.' },
      { q: 'Does LinkedIn Easy Apply skip the ATS?', a: 'No. Easy Apply feeds LinkedIn data directly into the company ATS, so the same rules apply.' },
      { q: 'What is a good ATS score?', a: 'Above 70/100 puts you in the top 25 percent of applicants. Above 85 is elite. Aim for 80+.' },
      { q: 'How do I know if a company uses an ATS?', a: 'Assume yes. 98% of Fortune 500 companies and around 70% of mid-size companies use one.' },
    ],
  },
  'resume-action-verbs': {
    slug: 'resume-action-verbs',
    title: '200+ Resume Action Verbs by Category (2026)',
    description: '210 resume verbs grouped by role (leadership, technical, sales, analysis + more). Weak-to-strong swap table plus 10 real bullet examples.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'resume action verbs',
    secondaryKeywords: ["strong resume verbs","action words for resume","power verbs resume","resume bullet verbs"],
    longTailKeywords: ["200 resume action verbs list","action verbs for leadership resume","action verbs for software engineer resume","weak to strong verb swap","resume verbs by category","past tense verbs for resume"],
    faqs: [
      { q: 'Should every bullet start with a different verb?', a: 'Within the same role, yes. Repeating the same verb three or four times makes the resume feel thin. Shoot for 80% unique verbs per role section.' },
      { q: 'What tense should resume verbs be in?', a: 'Past tense for all past roles. Present tense only for your current job. Mixing tenses within a single job is the most common grammar error recruiters flag.' },
      { q: 'Does the ATS care about action verbs?', a: 'Less than humans do. ATS parsers mostly match on nouns. But strong verbs still help because some ATS platforms weight bullets in the Verb + Result pattern higher.' },
    ],
  },
  'resume-length': {
    slug: 'resume-length',
    title: 'Resume Length 2026: 1 Page vs 2 Pages',
    description: 'How long should a resume be in 2026? 1 page under 5 years experience, 2 above. Full framework by career stage, industry, and cutting tactics.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'ideal resume length',
    secondaryKeywords: ["one page vs two page resume","resume pages 2026","how long should a resume be"],
    longTailKeywords: ["is a 2 page resume ok","resume length for experienced professionals","how long should a fresher resume be","does ATS care about resume length","how to cut resume to one page"],
    faqs: [
      { q: 'Can a resume be 1.5 pages?', a: 'No. Either fill page 2 to at least 60 percent or cut to 1 page. A half-empty page 2 looks sloppy.' },
      { q: 'Does resume length matter for ATS?', a: 'ATS parsers do not care about page count. They care about whether they can extract your content. A 1-page resume is no better or worse than 2 pages for parsing.' },
      { q: 'Should I have different-length resumes for different jobs?', a: 'Usually not. Keep one canonical version, tailor the skills section and summary. Only vary length across wildly different roles.' },
      { q: 'Can my resume be shorter than 1 page?', a: 'Only for very early fresher resumes. Half a page reads as "not enough to say".' },
    ],
  },
  'resume-summary-examples': {
    slug: 'resume-summary-examples',
    title: '25 Resume Summary Examples That Get Interviews',
    description: '15 summary examples by career stage + 10 by industry. Before/after versions, the 4-part formula, mistakes, and how to use AI without sounding generic.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'resume summary examples',
    secondaryKeywords: ["professional summary examples","resume summary formula","resume summary vs objective"],
    longTailKeywords: ["resume summary examples for freshers","resume summary examples software engineer","resume summary for career change","how many words in resume summary","resume summary with no experience"],
    faqs: [
      { q: 'How long should my resume summary be?', a: '40 to 90 words. Three to four sentences. Under three sentences reads thin; over five reads like bad Experience writing.' },
      { q: 'Do I need a summary if I have no experience?', a: 'Yes, a shortened one. For freshers: 2 sentences naming your degree, strongest project or internship with a number, and the role level you are targeting.' },
      { q: 'Do recruiters actually read the summary?', a: 'About 65 to 70 percent do. For them, a strong summary is the single highest-impact sentence on your resume.' },
    ],
  },
  'resume-format-guide': {
    slug: 'resume-format-guide',
    title: 'Best Resume Format 2026: Chronological vs Functional',
    description: 'The 3 resume formats compared: chronological, functional, hybrid. Which beats ATS, which recruiters trust, and the decision tree for your situation.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'best resume format',
    secondaryKeywords: ["chronological resume","functional resume","hybrid resume format","resume format 2026"],
    longTailKeywords: ["chronological vs functional resume","which resume format beats ATS","best resume format for experienced","best resume format for career change","resume format for freshers"],
    faqs: [
      { q: 'Is the functional resume really dead?', a: 'Essentially yes, for most job seekers. For any corporate application flow in 2026, use chronological or hybrid.' },
      { q: 'What resume format do FAANG companies prefer?', a: 'Chronological at SDE-I to SDE-II levels. Hybrid is acceptable at Staff+ for candidates with unusual breadth.' },
    ],
  },
  'quantify-resume-achievements': {
    slug: 'quantify-resume-achievements',
    title: 'How to Quantify Resume Achievements (2026 Guide)',
    description: 'Turn vague bullets into metric-driven proof. The XYZ formula, 9 places to find numbers, and 50+ quantified bullet examples across 8 roles.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'quantify resume achievements',
    secondaryKeywords: ["resume metrics","XYZ formula resume","measurable bullets resume"],
    longTailKeywords: ["how to quantify achievements without numbers","resume bullets with metrics examples","XYZ formula for resume bullets","how to add metrics to resume","quantified resume examples"],
    faqs: [
      { q: 'How many bullets on my resume should have numbers?', a: 'At least 60%. Ideally every bullet has at least one piece of quantification: a count, percentage, scale, or timeframe.' },
      { q: 'Can I round numbers for readability?', a: 'Yes, within reason. Round to the nearest easily-grasped figure (14k not 14,237), but do not inflate.' },
      { q: 'Should I use % or absolute numbers?', a: 'Both when possible. Cut CAC 40% (Rs 1,200 to Rs 720) is stronger than either alone.' },
    ],
  },
  'cover-letter-vs-resume': {
    slug: 'cover-letter-vs-resume',
    title: 'Cover Letter vs Resume: Do You Need Both?',
    description: 'Do you still need a cover letter in 2026? Honest answer with data. When to write one, when to skip, and the hidden cost of going without.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'cover letter vs resume',
    secondaryKeywords: ["do you need a cover letter","cover letter importance 2026"],
    longTailKeywords: ["is a cover letter necessary in 2026","when to skip a cover letter","cover letter vs resume differences","how long should a cover letter be","do recruiters read cover letters"],
    faqs: [
      { q: 'How long should a cover letter be?', a: '200 to 400 words. 3 to 4 short paragraphs. Always 1 page.' },
      { q: 'Do I write a new cover letter for every application?', a: 'Paragraphs 1 and 2 need substantive tailoring. Paragraph 3 can be recycled across similar roles with minor tweaks.' },
      { q: 'Can I just paste my resume into a cover letter?', a: 'No. A cover letter repeating resume bullets is wasted space.' },
    ],
  },
  'tailor-resume': {
    slug: 'tailor-resume',
    title: 'How to Tailor Your Resume in 10 Minutes',
    description: 'Tailored resumes get 3x more callbacks. The minute-by-minute process to customize for any JD without starting over. AI-assisted workflow included.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'how to tailor a resume',
    secondaryKeywords: ["tailored resume","resume tailoring","JD matching resume"],
    longTailKeywords: ["how to tailor resume in 10 minutes","tailor resume for job description","AI resume tailoring","how much tailoring is too much","resume tailoring checklist"],
    faqs: [
      { q: 'Should I tailor for every application?', a: 'For every application you actually care about, yes. For low-intent mass postings, a 2-minute tailoring of the summary + top 3 bullets is still worth it.' },
      { q: 'How much tailoring is too much?', a: 'If you are editing 5+ bullets per application or making structural changes, you are over-tailoring. Keep a clean master resume; tailor deltas only.' },
      { q: 'Can AI do the full tailoring for me?', a: 'It can draft, but review every output. AI hallucinates numbers and can list skills you do not have.' },
    ],
  },
  'best-free-resume-builder': {
    slug: 'best-free-resume-builder',
    title: 'Free vs Paid Resume Builders 2026: Honest Review',
    description: '8 resume builders compared honestly: pricing, privacy, ATS compatibility, AI. Which "free" builders paywall the download. Open-source options.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'best free resume builder',
    secondaryKeywords: ["free vs paid resume builder","online resume maker","ATS resume builder"],
    longTailKeywords: ["free resume builder no paywall","best ATS-friendly resume builder","open source resume builder","resume builder with AI","truly free resume builders comparison"],
    faqs: [
      { q: 'Is there a truly 100% free resume builder?', a: 'Yes. Indeed Resume Builder, ResumeBuildz, and open-source tools all offer full-function build + export without paywalls.' },
      { q: 'Do paid resume builders produce better resumes?', a: 'Not inherently. What you write matters far more than which builder you use.' },
      { q: 'How do I cancel a resume builder trial?', a: 'Set a calendar reminder for 48 hours before the trial ends. Cancel via account settings; if that fails, email support AND dispute with your card issuer.' },
    ],
  },
  'ai-resume-builders-tested': {
    slug: 'ai-resume-builders-tested',
    title: 'AI Resume Builders 2026: We Tested 8',
    description: 'We tested 8 AI resume tools with the same input. What AI does well, what it hallucinates, privacy gotchas, and 5 rules for using AI honestly.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-04-19',
    dateModified: '2026-04-19',
    primaryKeyword: 'AI resume builders',
    secondaryKeywords: ["AI resume writer","ChatGPT resume","AI cover letter generator"],
    longTailKeywords: ["best AI resume builder 2026","AI resume tools tested","does AI resume get rejected","can ATS detect AI written resume","AI resume hallucinations"],
    faqs: [
      { q: 'Is it ethical to use AI for my resume?', a: 'Yes, with limits. AI as editor is widely accepted; AI as inventor is fraud. Every fact on your resume must be true whether AI helped phrase it or not.' },
      { q: 'Will I get rejected for using AI?', a: 'Not for using it well. You will get rejected (or fired in onboarding) if AI invented achievements you cannot discuss in interview.' },
      { q: 'Can ATS detect AI-written resumes?', a: 'Some can, most cannot yet in 2026. Humans detect AI writing more reliably: recruiters flag AI-generated resumes 61% of the time after light training.' },
    ],
  },
  'fresher-resume': {
    slug: 'fresher-resume',
    title: 'Fresher Resume Format 2026 (7-Section Template)',
    description: 'The exact 7-section fresher resume format that beats Indian and global ATS. Built for campus placements, NQT/InfyTQ, and off-campus drives.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-14',
    dateModified: '2026-04-15',
    primaryKeyword: 'fresher resume format',
    secondaryKeywords: ["resume for freshers","fresher resume template","first job resume"],
    longTailKeywords: ["fresher resume format 2026","7 section fresher resume","resume format for BTech freshers","fresher resume no experience","best resume template for freshers"],
  },
  'resume-tips': {
    slug: 'resume-tips',
    title: 'Resume Writing Tips That Actually Work',
    description: 'The practical resume tips recruiters wish candidates followed. Quantified bullets, action verbs, the one-page rule, filename rules, proofread checklist.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-03-20',
    dateModified: '2026-04-19',
    primaryKeyword: 'resume writing tips',
    secondaryKeywords: ["resume tips","resume advice","resume mistakes"],
    longTailKeywords: ["resume tips from recruiters","how to improve your resume","resume writing tips 2026","resume tips for freshers","resume tips for experienced"],
    faqs: [
      { q: 'How often should I update my resume?', a: 'At minimum, every 6 months even when not actively job searching. Record new wins while they are fresh.' },
      { q: 'Should I include my photo?', a: 'In India: only if customer-facing. In the US / UK / Canada: never. Many ATS systems flag photos.' },
      { q: 'Do I need a references section?', a: 'No. References available on request is also unnecessary. Use that space for a stronger section.' },
    ],
  },
  'ats-guide': {
    slug: 'ats-guide',
    title: 'How to Beat ATS: The Complete Guide',
    description: '75% of resumes never reach a human. Here is how ATS works, why yours is filtered, and exactly how to fix it. 10 tactics + per-system tuning.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-02-15',
    dateModified: '2026-04-19',
    primaryKeyword: 'beat ATS',
    secondaryKeywords: ["ATS guide","applicant tracking system tips","ATS resume optimization"],
    longTailKeywords: ["how to beat applicant tracking system","does every company use ATS","ATS resume format","ATS keyword matching","ATS score improvement"],
    faqs: [
      { q: 'Does every company use an ATS?', a: '98% of Fortune 500 companies do. Roughly 70% of mid-size companies do. Assume yes unless the posting is from a small shop.' },
      { q: 'Will an ATS reject my resume for typos?', a: 'Not directly, but yes indirectly. A typo in Python becomes Pthyon and the ATS does not match it against the JD Python requirement.' },
      { q: 'Is PDF or DOCX better for ATS?', a: 'Both are excellent on modern parsers. Marginally, selectable-text PDF is safer. Unless the posting explicitly asks for DOCX, use PDF.' },
    ],
  },
  'resume-after-layoff': {
    slug: 'resume-after-layoff',
    title: 'Resume After a Layoff: 5-Step Guide for 2026',
    description: '350,000+ tech workers were laid off since 2024. The 5-step playbook to rewrite your resume with no apologetic tone and no awkward gaps.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-04-14',
    dateModified: '2026-04-15',
    primaryKeyword: 'resume after layoff',
    secondaryKeywords: ["layoff resume","resume after being laid off","resume after tech layoff"],
    longTailKeywords: ["how to explain layoff on resume","resume after Meta layoff","should I mention layoff on resume","resume after company restructuring","explaining layoff in cover letter"],
  },
  'resume-after-career-gap': {
    slug: 'resume-after-career-gap',
    title: 'How to Write a Resume After a Career Gap',
    description: 'A career gap is not a deal-breaker. 62% of professionals have non-linear paths. Here is how to address the gap honestly and still get interviews.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-04-14',
    dateModified: '2026-04-15',
    primaryKeyword: 'resume after career gap',
    secondaryKeywords: ["resume with gaps","career gap resume","how to explain gap in resume"],
    longTailKeywords: ["how to explain career gap on resume","resume after maternity break","resume after 2 year gap","career gap resume example","hiding career gap on resume"],
  },
  'resume-for-career-change': {
    slug: 'resume-for-career-change',
    title: 'Resume for Career Change: 5-Step Pivot Guide',
    description: 'Transferable-skills rewriting, hybrid format, 6 common pivot examples, realistic 12-month timeline, and an informational interview email template.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-04-14',
    dateModified: '2026-04-15',
    primaryKeyword: 'resume for career change',
    secondaryKeywords: ["career change resume","career pivot resume","transferable skills resume"],
    longTailKeywords: ["resume for career change examples","how to write career change resume","transferable skills on resume","career change resume template","resume for pivoting careers"],
  },
  'cover-letter': {
    slug: 'cover-letter',
    title: 'Cover Letter Guide & Templates (2026)',
    description: 'How to write a cover letter that pairs with a strong resume. 4-part structure, complete example, 6 industry templates, mistakes, FAQ.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-03-15',
    dateModified: '2026-04-19',
    primaryKeyword: 'how to write a cover letter',
    secondaryKeywords: ["cover letter template","cover letter examples","cover letter format"],
    longTailKeywords: ["cover letter template 2026","cover letter for freshers","cover letter vs email","how long should a cover letter be","cover letter ending examples"],
    faqs: [
      { q: 'Do I still need a cover letter in 2026?', a: 'Yes, in most cases. 83% of hiring managers read cover letters when included. Roughly 1 in 4 recruiters treats a missing cover letter as a silent disqualifier.' },
      { q: 'How long should a cover letter be?', a: '250 to 400 words, 3 to 4 paragraphs, always under 1 page.' },
      { q: 'Should I use the same cover letter for multiple applications?', a: 'Paragraphs 1 and 2 must be tailored per application. Paragraph 3 can be recycled across similar roles.' },
    ],
  },
  'campus-placement-resume': {
    slug: 'campus-placement-resume',
    title: 'Campus Placement Resume 2026 (India)',
    description: 'The 10-point checklist + 5-round process walkthrough for Indian campus placements. Built around TCS NQT, Infosys InfyTQ, and Wipro Elite NTH.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-04-14',
    dateModified: '2026-04-15',
    primaryKeyword: 'campus placement resume',
    secondaryKeywords: ["campus resume","Indian placement resume","college placement resume"],
    longTailKeywords: ["campus placement resume 2026","resume for TCS NQT","resume for InfyTQ","resume for Wipro Elite","best resume format for placements"],
  },
  'why-should-we-hire-you': {
    slug: 'why-should-we-hire-you',
    title: 'How to Answer "Why Should We Hire You" (8 Examples)',
    description: 'The 3-pillar formula (Problem, Proof, Compounding), 8 worked examples from fresher to executive, and the 6 mistakes that kill this answer.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-05-12',
    dateModified: '2026-05-12',
    publishAt: '2026-05-12T04:43:00Z',
    primaryKeyword: 'why should we hire you',
    secondaryKeywords: ['why should we hire you answer', 'interview closing question', 'why hire you', 'interview pitch'],
    longTailKeywords: ['why should we hire you sample answer', 'why should we hire you fresher', 'why should we hire you over other candidates', 'best answer to why should we hire you', 'why should we hire you for software engineer'],
    faqs: [
      { q: 'Is this same as Why do you want this role?', a: 'Related but different. Why do you want this role = motivation; Why should we hire you = value.' },
      { q: 'What if I cannot name a specific problem?', a: 'Do more research. Earnings calls, blog, LinkedIn of the team, and the JD together give you the problem.' },
      { q: 'Can I memorise word-for-word?', a: 'No. Memorise the 3-pillar structure; fresh phrasing on the day keeps the answer human.' },
      { q: 'How do I handle this as a fresher?', a: 'Substitute Proof with your strongest project or internship plus a number.' },
    ],
  },
  'resume-margins-spacing': {
    slug: 'resume-margins-spacing',
    title: 'Resume Margins & Spacing: Ideal Setup (2026)',
    description: 'Exact margin, line-height, and section-spacing values that make a resume feel professional and parse cleanly on ATS. 8-point spec plus layout fixes.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-05-14',
    dateModified: '2026-05-14',
    publishAt: '2026-05-14T05:59:00Z',
    primaryKeyword: 'resume margins',
    secondaryKeywords: ['resume spacing', 'resume line height', 'resume layout', 'resume formatting'],
    longTailKeywords: ['ideal resume margins in inches', 'resume margins for Word', 'resume line spacing 2026', 'resume section spacing', 'how to fix cramped resume'],
    faqs: [
      { q: 'Are 0.5 in margins too tight?', a: 'Marginal. 0.5 in is the minimum safe value; preferred is 0.7 to 0.75 in.' },
      { q: 'Does ATS care about margins?', a: 'Not directly. ATS parses text; margins affect how much fits and the resulting layout.' },
      { q: 'Is 1.0 line-height too tight?', a: 'Yes. Minimum 1.15, preferred 1.2 for body bullets.' },
    ],
  },
  'workday-resume-tips': {
    slug: 'workday-resume-tips',
    title: 'Workday Resume Tips That Actually Pass (2026)',
    description: 'How Workday parses your resume, 8 tactical tips that raise your match score, and the Profile Sync gotcha that catches most candidates.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-05-17',
    dateModified: '2026-05-17',
    publishAt: '2026-05-17T05:11:00Z',
    primaryKeyword: 'Workday resume tips',
    secondaryKeywords: ['Workday ATS', 'Workday resume parsing', 'Workday applicant tracking', 'Workday profile'],
    longTailKeywords: ['how to pass Workday ATS', 'Workday resume format', 'Workday profile sync issue', 'companies that use Workday', 'Workday resume upload best practices'],
    faqs: [
      { q: 'PDF or DOCX for Workday?', a: 'Both parse equally well. Default to PDF unless posting says DOCX.' },
      { q: 'Why does Workday show my old resume after new upload?', a: 'Profile Sync caches across tenants. Use Edit Profile flow on new tenant, or fresh account.' },
      { q: 'How many skills should I add?', a: '10 to 20 mapped to JD; first 10 are what recruiters see on candidate card.' },
    ],
  },
  'star-method-examples': {
    slug: 'star-method-examples',
    title: 'STAR Method for Behavioural Interviews: 8 Full Examples',
    description: 'The 90-second STAR formula, 8 full worked examples across Tech, Product, Design, Finance, Marketing, Management, and HR, and the 6 mistakes that tank behavioural answers.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-05-05',
    dateModified: '2026-05-05',
    publishAt: '2026-05-05T04:41:00Z',
    primaryKeyword: 'STAR method examples',
    secondaryKeywords: ['STAR method interview', 'behavioural interview framework', 'situation task action result', 'STAR technique'],
    longTailKeywords: ['STAR method examples for tell me about yourself', 'STAR answer for greatest weakness', 'behavioural interview STAR template', 'how to use STAR method in interview', 'STAR method examples software engineer', 'STAR interview answers for conflict'],
    faqs: [
      { q: 'How old can a STAR story be?', a: 'Ideally within the last 18 to 24 months. For senior candidates, strongest-ever story can be older if nothing recent matches the scope.' },
      { q: 'Can I use the same story for two questions?', a: 'Yes, in different rounds. Never in the same round.' },
      { q: 'What if my Result does not have a number?', a: 'Find one. Users, time saved, tickets closed, revenue. Qualitative-only results make weak anchor stories.' },
      { q: 'Does STAR work for technical interviews?', a: 'For the behavioural / project walk-through portion, yes. For coding and systems design, use structured problem-solving frames.' },
      { q: 'How do I answer tell me about a failure without tanking the interview?', a: 'Pick a real failure, own your role, end with the Lesson Learned beat and a concrete example of applying it later.' },
    ],
  },
  'best-resume-fonts': {
    slug: 'best-resume-fonts',
    title: 'Best Resume Fonts 2026 (Tested Against 4 ATS)',
    description: '10 resume fonts tested on Workday, Greenhouse, Lever, and Taleo. Safe picks, fonts to avoid, size rules, and PDF embedding tips for parsing at 100 percent.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-05-07',
    dateModified: '2026-05-07',
    publishAt: '2026-05-07T06:07:00Z',
    primaryKeyword: 'best resume fonts',
    secondaryKeywords: ['resume font size', 'ATS safe fonts', 'professional resume font', 'resume typography'],
    longTailKeywords: ['best resume font for ATS', 'Calibri vs Arial for resume', 'resume font size 10 or 11', 'is Times New Roman good for resume', 'best font pairing for resume', 'how to embed fonts in resume PDF'],
    faqs: [
      { q: 'Is Calibri or Arial better for a resume?', a: 'Calibri, slightly. Designed for screens, tighter letter spacing, parses identically to Arial on every modern ATS.' },
      { q: 'Can I use 2 fonts on my resume?', a: 'Yes, sparingly: one serif for name + headings, one sans-serif for body. Never 3.' },
      { q: 'Does font affect ATS parsing in PDF?', a: 'Only if the font is not embedded or not available on ATS side. Embedded PDFs with system-standard fonts parse at 100 percent.' },
      { q: 'What is the minimum readable font size?', a: '10 pt for body on 2-page resumes; 10.5 to 11 pt for 1-page. Under 10 pt reads cramped.' },
    ],
  },
  'wipro-elite-nth-guide': {
    slug: 'wipro-elite-nth-guide',
    title: 'Wipro Elite NTH 2026: Syllabus, Process & Resume',
    description: 'Complete Wipro NTH 2026 guide: 3-round process, full syllabus, offer types (Elite Hire vs Turbo Hire), resume placement, and the 45-day prep plan.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-05-10',
    dateModified: '2026-05-10',
    publishAt: '2026-05-10T05:18:00Z',
    primaryKeyword: 'Wipro Elite NTH',
    secondaryKeywords: ['Wipro NTH syllabus', 'Wipro NTH process', 'Wipro Elite Hire salary', 'Wipro Turbo Hire'],
    longTailKeywords: ['Wipro NTH 2026 syllabus PDF', 'how to prepare for Wipro NTH', 'Wipro Elite Hire vs Turbo Hire', 'Wipro NTH eligibility criteria', 'Wipro NTH registration 2026', 'Wipro NTH previous year questions'],
    faqs: [
      { q: 'What is the eligibility for Wipro Elite NTH?', a: 'B.E. / B.Tech / M.E. / M.Tech / 5-yr Integrated M.Tech, 60 percent throughout 10th, 12th, UG; no active backlogs; within eligible graduation year.' },
      { q: 'What is the difference between Elite Hire and Turbo Hire?', a: 'Elite Hire is Rs 3.5 LPA standard; Turbo Hire is Rs 6.5 LPA accelerated track for top 10 percent coding scorers.' },
      { q: 'Is there a bond at Wipro?', a: 'Typically a 15-month service agreement with financial penalty for early exit.' },
      { q: 'Can I reapply if I fail NTH?', a: 'Yes, within your eligible graduation year window. No cap on attempts.' },
    ],
  },
  'tell-me-about-yourself': {
    slug: 'tell-me-about-yourself',
    title: 'How to Answer "Tell Me About Yourself" (10 Examples)',
    description: 'The 3-part present-past-future formula, 10 worked examples by career stage, and the 6 mistakes that tank this first-interview question.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-04-28',
    dateModified: '2026-04-28',
    primaryKeyword: 'tell me about yourself',
    secondaryKeywords: ["tell me about yourself answer","elevator pitch","self introduction interview"],
    longTailKeywords: ["tell me about yourself examples","tell me about yourself fresher","60 second pitch interview","self introduction in interview","tell me about yourself sample answer"],
    publishAt: '2026-04-28T05:38:00Z',
    faqs: [
      { q: 'How long should the answer be?', a: 'Target 60 to 90 seconds. Under 45 seconds reads low-effort; over 120 seconds reads as poorly edited.' },
      { q: 'Should I memorise word-for-word?', a: 'No. Memorise 3 beats (Present, Past, Future) and hit them. Fresh phrasing on the day sounds human; a rehearsed script sounds robotic.' },
      { q: 'Do I need to mention the company name?', a: 'Once, in the Future section. Naming the company + a specific reason signals you did your homework.' },
      { q: 'Can I use the same answer for every company?', a: 'Present and Past stay stable; Future must change per company. It is the only part that tailors the rest.' },
      { q: 'Is it OK to use notes?', a: 'Yes, 5 to 7 keywords on a notepad. Not a full script. Glancing at keywords keeps you on track without reading robotically.' },
    ],
  },
  'linkedin-url-on-resume': {
    slug: 'linkedin-url-on-resume',
    title: 'Should You Put LinkedIn URL on Your Resume?',
    description: 'Yes, if your profile passes the 8-point readiness check. 4 reasons to include it, 4 cases where you should not, and the correct formatting in 2026.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-30',
    dateModified: '2026-04-30',
    primaryKeyword: 'LinkedIn URL on resume',
    secondaryKeywords: ["LinkedIn on resume","LinkedIn profile on resume","resume contact info"],
    longTailKeywords: ["should I put LinkedIn on resume","how to add LinkedIn to resume","LinkedIn URL format","resume header LinkedIn","should resume have GitHub and LinkedIn"],
    publishAt: '2026-04-30T05:23:00Z',
    faqs: [
      { q: 'Is it OK to hyperlink LinkedIn in a PDF?', a: 'Yes, preferred. Keep the display text as the short URL (linkedin.com/in/yourname), not raw https.' },
      { q: 'What if I do not have a LinkedIn at all?', a: 'Create one, even a minimal one. No LinkedIn reads as a red flag for roles above entry-level.' },
      { q: 'Does the ATS care about the LinkedIn URL?', a: 'Some ATS parse and pre-populate candidate profiles from it; most do not. A recruiter will click it manually in the next step.' },
      { q: 'Can I skip LinkedIn for design roles?', a: 'You can skip the URL but add your portfolio or Behance / Dribbble. Zero online presence reads as concerning for creative roles.' },
    ],
  },
  'infosys-infytq-guide': {
    slug: 'infosys-infytq-guide',
    title: 'Infosys InfyTQ Certification: Full 2026 Guide',
    description: 'The complete Infosys InfyTQ 2026 guide: 5-phase process, Foundation + Advanced syllabus, roles on offer, HackWithInfy, and resume placement.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-04-30',
    dateModified: '2026-04-30',
    primaryKeyword: 'Infosys InfyTQ',
    secondaryKeywords: ["InfyTQ certification","Infosys Springboard","HackWithInfy"],
    longTailKeywords: ["Infosys InfyTQ 2026","InfyTQ foundation syllabus","InfyTQ advanced certification","HackWithInfy rounds","Infosys Systems Engineer"],
    publishAt: '2026-05-03T05:54:00Z',
    faqs: [
      { q: 'Is InfyTQ Foundation free?', a: 'Yes. Foundation track + assessment is fully free. Advanced has a modest fee that colleges often subsidise.' },
      { q: 'What is the pass mark for Foundation Certification?', a: '65 percent overall. Some years enforce sectional cut-offs of 55 percent per subject.' },
      { q: 'Can I retake the Foundation Assessment?', a: 'Yes, up to 2 to 3 retake attempts per year with a 30 to 60 day cooling period.' },
      { q: 'Is the Advanced certification worth the fee?', a: 'Yes if targeting Digital Specialist Engineer (Rs 6.5 LPA) or above. Salary delta pays back the fee in a week of work.' },
      { q: 'What is the bond at Infosys?', a: 'Typically 2 years with a Rs 50,000 penalty for early exit.' },
    ],
  },
  'interview-questions-and-answers': {
    slug: 'interview-questions-and-answers',
    title: '100 Common Interview Questions & Answers (2026)',
    description: 'The 100 questions hiring managers actually ask in 2026 across behavioural, situational, technical, leadership, culture, tricky, and closing. STAR method + 48-hour prep plan.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-04-21',
    dateModified: '2026-04-21',
    primaryKeyword: 'common interview questions',
    secondaryKeywords: ["interview questions and answers","top interview questions 2026","behavioural interview questions"],
    longTailKeywords: ["100 common interview questions with answers","behavioural interview questions STAR","technical interview questions","tricky interview questions","interview questions to expect"],
    faqs: [
      { q: 'Should I memorise answers word-for-word?', a: 'No. Memorise structure (STAR) and your 6 to 8 stories. Variations in wording make you sound human; rehearsed scripts sound robotic.' },
      { q: 'How long should my answers be?', a: '60 to 120 seconds for behavioural, 2 to 4 minutes for technical deep dives. If you are over 2 minutes on a behavioural, you are padding.' },
      { q: 'Is it OK to say I do not know?', a: 'Yes, paired with how you would find out. Bluffing loses more offers than admitting a gap.' },
      { q: 'How do I answer when I do not have the exact experience they want?', a: 'Bridge with the closest equivalent plus learning speed. "I have not used X, but I shipped Y which solves the same problem."' },
      { q: 'What if I bomb one question?', a: 'Acknowledge, move on. "Let me come back to that" works. Do not let one weak answer hijack the rest of the round.' },
    ],
  },
  'resume-skills-list': {
    slug: 'resume-skills-list',
    title: 'How to List Skills on a Resume by Type (2026)',
    description: 'Hard skills, soft skills, languages, certifications, tools — each lands differently with ATS and recruiters. Exact grouping, order, and formatting to use.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-04-23',
    dateModified: '2026-04-23',
    primaryKeyword: 'how to list skills on resume',
    secondaryKeywords: ["resume skills section","hard skills resume","soft skills resume","resume skills by type"],
    longTailKeywords: ["how to list soft skills on resume","resume skills section examples","list of hard skills for resume","how many skills on resume","certifications on resume"],
    publishAt: '2026-04-23T06:12:00Z',
    faqs: [
      { q: 'How many skills should I list?', a: '10 to 15 hard skills, grouped into 3 to 5 categories. Fewer reads thin, more reads padded.' },
      { q: 'Should I list skill proficiency levels?', a: 'Only if you use a defensible scale (years of experience or CEFR for languages). Avoid star ratings.' },
      { q: 'Are soft skills worth listing?', a: 'Rarely in a dedicated list. Prove them in Experience bullets instead.' },
      { q: 'Should I list Microsoft Office?', a: 'No, unless the JD asks for advanced Excel. Basic office software is assumed.' },
    ],
  },
  'tcs-nqt-resume-guide': {
    slug: 'tcs-nqt-resume-guide',
    title: 'TCS NQT 2026: Resume & Process Guide for Freshers',
    description: 'Complete TCS NQT 2026 playbook: 5-round process, resume format that clears TCS iON parsing, 25 keywords, 3 project templates, and the application timeline.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-04-26',
    dateModified: '2026-04-26',
    primaryKeyword: 'TCS NQT resume',
    secondaryKeywords: ["TCS NQT 2026","TCS NQT syllabus","TCS iON resume","TCS Ninja resume"],
    longTailKeywords: ["TCS NQT resume format","TCS NQT process 2026","TCS NQT interview questions","TCS Ninja vs Digital","TCS NQT cut off"],
    publishAt: '2026-04-26T05:05:00Z',
    faqs: [
      { q: 'What is the cut-off for TCS NQT 2026?', a: 'Historically around 55 to 60 percent overall with ~60 percent sectional. Advanced NQT cut-off is roughly 65 percent.' },
      { q: 'Is TCS NQT score valid for other companies?', a: '500+ corporates accept NQT scores including Cognizant, Mindtree, HCL, Capgemini, LTIMindtree. Valid 12 to 24 months.' },
      { q: 'What CGPA do I need?', a: '60 percent throughout (10th, 12th, UG). Above 7.5 CGPA puts you in the strong pile; above 8.5 makes you Digital / Prime eligible.' },
      { q: 'Are backlogs a dealbreaker?', a: 'Current active backlogs disqualify. Past cleared backlogs are fine if declared honestly.' },
      { q: 'What is the bond period?', a: '2 years for Ninja / Digital with Rs 50,000 penalty for early exit.' },
    ],
  },
  'naukri-resume-tips': {
    slug: 'naukri-resume-tips',
    title: '8 Naukri Resume Tips That 3x Recruiter Views',
    description: 'Naukri 90M candidates and 350k recruiters work off filters, not browsing. Here is how to rank higher in the search results that matter.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-04-14',
    dateModified: '2026-04-15',
    primaryKeyword: 'Naukri resume tips',
    secondaryKeywords: ["Naukri profile","Naukri vs LinkedIn India","Naukri recruiter views"],
    longTailKeywords: ["how to get more Naukri views","Naukri resume keywords","optimise Naukri profile 2026","Naukri profile headline examples","Naukri resume format"],
  },
  'technical-interview-prep': {
    slug: 'technical-interview-prep',
    title: 'Technical Interview Prep: The 90-Day Plan (2026)',
    description: 'A realistic 12 week plan from shaky on arrays to offer-ready at FAANG. Problem counts per week, mock schedule, systems design framework, and resource stack.',
    category: 'Technical Interview Prep',
    categorySlug: 'technical-interview',
    datePublished: '2026-05-26',
    dateModified: '2026-05-26',
    publishAt: '2026-05-26T04:38:00Z',
    primaryKeyword: 'technical interview prep',
    secondaryKeywords: ['coding interview preparation','FAANG interview prep','software engineer interview prep','DSA interview prep'],
    longTailKeywords: ['90 day technical interview prep plan','how to prepare for FAANG interview','leetcode preparation plan','system design interview prep','how many leetcode problems for FAANG','technical interview prep roadmap'],
    faqs: [
      { q: 'How many LeetCode problems should I solve before a FAANG interview?', a: 'Between 200 and 300 well understood problems, heavy on mediums. Quality over count.' },
      { q: 'Is LeetCode premium worth the money?', a: 'Yes, but only from week 9 onwards. Company tagged questions and sort by frequency make the final 4 weeks dramatically more targeted.' },
      { q: 'How many hours per day is realistic?', a: '2 to 3 on weekdays, 5 to 6 on weekends. Any more and you burn out by week 8.' },
      { q: 'Do I need to know a specific language?', a: 'Pick one and stick with it. Python is fastest, C++ is competitive, Java is common at enterprise.' },
      { q: 'How much systems design do I need as a new grad?', a: 'Usually zero. New grad loops focus on coding and behavioural.' },
      { q: 'Should I apply while still prepping?', a: 'Start applying around week 8. Interview loops take 3 to 5 weeks to schedule.' },
    ],
  },
  'linkedin-easy-apply': {
    slug: 'linkedin-easy-apply',
    title: 'LinkedIn Easy Apply: Skip or Use? (2026)',
    description: 'Is LinkedIn Easy Apply a black hole or useful speed channel? Data from a 1000 application study, when to use, when to skip, and the 6 point ready check.',
    category: 'Job Search Strategy',
    categorySlug: 'job-search-strategy',
    datePublished: '2026-05-28',
    dateModified: '2026-05-28',
    publishAt: '2026-05-28T06:04:00Z',
    primaryKeyword: 'LinkedIn Easy Apply',
    secondaryKeywords: ['LinkedIn easy apply vs direct apply','LinkedIn job search tips','LinkedIn application strategy','does easy apply work'],
    longTailKeywords: ['is LinkedIn easy apply worth it','LinkedIn easy apply response rate','how many easy apply jobs to apply','easy apply vs company website','LinkedIn easy apply tips','LinkedIn easy apply black hole'],
    faqs: [
      { q: 'Is LinkedIn Easy Apply worth it in 2026?', a: 'Worth using for first 12 hours after a role is posted, for small to mid-size companies, as a secondary channel.' },
      { q: 'How many Easy Apply jobs should I apply to?', a: 'Cap at 10 per day on quality roles.' },
      { q: 'Does LinkedIn Easy Apply bypass the ATS?', a: 'No. Most companies sync Easy Apply into Greenhouse, Lever, or Workday.' },
      { q: 'Why do I never hear back from Easy Apply?', a: 'Roughly 2 percent of Easy Applies result in a callback.' },
      { q: 'Should I use the LinkedIn cover letter box?', a: 'Yes, 3 to 5 sentences max. Name the role, 1 specific matching skill, 1 why-this-company line.' },
      { q: 'Does Open to Work hurt my chances?', a: 'Recruiters-only mode increases inbound 3x. Visible green frame is neutral to slightly negative in some industries.' },
    ],
  },
  'resume-after-parental-leave': {
    slug: 'resume-after-parental-leave',
    title: 'Resume After Maternity or Paternity Leave (2026)',
    description: 'How to address a parental career break honestly. Framing that works, a stayed-sharp list, 4 summary examples, returnship programmes, and the flex conversation.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-05-31',
    dateModified: '2026-05-31',
    publishAt: '2026-05-31T05:16:00Z',
    primaryKeyword: 'resume after maternity leave',
    secondaryKeywords: ['resume after parental leave','returning to work after baby','career gap resume maternity','returnship resume'],
    longTailKeywords: ['how to write resume after maternity break','resume after 2 year maternity leave','returning to work after paternity leave','returnship programs India','how to explain parental leave on resume','mom returning to work resume'],
    faqs: [
      { q: 'How do I explain a 2 year maternity break on my resume?', a: 'List it as timeline entry: Parental leave and caregiving, Jan 2024 to Mar 2026. Follow with 1 or 2 stayed-sharp bullets.' },
      { q: 'Should I leave the gap blank?', a: 'No. Blank gaps create worse assumptions than named ones.' },
      { q: 'Do recruiters discriminate against parental leave?', a: 'Legally they cannot; in practice, bias exists. Counter with stayed-sharp evidence.' },
      { q: 'Is a functional resume better when I have a gap?', a: 'No. Hybrid or chronological wins.' },
      { q: 'How do I answer gap questions in interviews?', a: 'Two sentences, factual and forward: took 18 months parental leave, completed AWS cert + 2 freelance engagements, fully re-engaged now.' },
    ],
  },
  'questions-to-ask-interviewer': {
    slug: 'questions-to-ask-interviewer',
    title: '40 Questions to Ask the Interviewer (and 5 to Avoid)',
    description: '40 field-tested questions to ask at the end of an interview across role, team, growth, company, culture, red flags. Plus 5 to avoid and what to do out of time.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-06-02',
    dateModified: '2026-06-02',
    publishAt: '2026-06-02T04:49:00Z',
    primaryKeyword: 'questions to ask in interview',
    secondaryKeywords: ['questions to ask interviewer', 'questions to ask at end of interview', 'good interview questions to ask', 'questions to ask hiring manager'],
    longTailKeywords: ['best questions to ask at end of interview', 'smart questions to ask in interview', 'questions to ask for senior role interview', 'questions to ask about team culture', 'red flag questions to ask interviewer', 'questions to ask when interviewing for a manager role'],
    faqs: [
      { q: 'How many questions should I ask?', a: '2 or 3 per interviewer in a 45-minute loop. 1 if time is tight.' },
      { q: 'Is it okay to ask the same question to different interviewers?', a: 'Yes, for questions like what does success look like.' },
      { q: 'Can I write my questions down?', a: 'Yes. Short list in a notebook. Signals preparation; do not read word for word.' },
      { q: 'What if all my questions were already answered?', a: 'Pivot: You touched on X earlier, I would love to go one level deeper.' },
      { q: 'Should I ask about salary in the final round?', a: 'Only if recruiter has not shared a band and hiring manager brings it up first.' },
      { q: 'What question leaves the best impression?', a: 'What is the trade-off the team is debating is one of the strongest closers.' },
    ],
  },
  'resume-keywords-by-industry': {
    slug: 'resume-keywords-by-industry',
    title: 'Resume Keywords by Industry: 12 Industries (2026)',
    description: '20 to 30 ATS resume keywords per industry across 12 industries, plus a 3-minute method to extract role-specific keywords from any job description.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-06-04',
    dateModified: '2026-06-04',
    publishAt: '2026-06-04T05:51:00Z',
    primaryKeyword: 'resume keywords',
    secondaryKeywords: ['resume keywords by industry', 'ATS keywords list', 'industry resume keywords', 'JD keywords resume'],
    longTailKeywords: ['resume keywords for tech jobs', 'resume keywords for finance', 'healthcare resume keywords', 'marketing resume keywords', 'how to find keywords for resume', 'ATS keywords for software engineer'],
    faqs: [
      { q: 'How many keywords should a resume have?', a: 'Target 60 to 80 percent match with JD hard skills. Typically 25 to 40 keywords across the whole resume.' },
      { q: 'Do keywords need to be exact match?', a: 'For ATS match, yes. Google Analytics 4 and GA4 might not resolve to the same keyword.' },
      { q: 'Is keyword stuffing always bad?', a: 'Yes. Modern ATS run density checks and penalise obvious stuffing.' },
      { q: 'How do I find keywords if JD is short?', a: 'Pull JDs from 3 or 4 similar roles at peer companies. Keywords in all of them are the industry-wide must-haves.' },
      { q: 'Does LinkedIn use same keyword match?', a: 'Yes, Recruiter search runs on keyword match. Mirror resume keywords in About + headline.' },
    ],
  },
  'resume-over-50': {
    slug: 'resume-over-50',
    title: 'Resume for Over 50: How to Beat Age Bias (2026)',
    description: 'Age bias is real and measurable. 7 tactics to neutralise age signals on a resume for workers over 50, plus 4 worked summaries.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-06-07',
    dateModified: '2026-06-07',
    publishAt: '2026-06-07T05:07:00Z',
    primaryKeyword: 'resume over 50',
    secondaryKeywords: ['resume for older workers', 'senior resume tips', 'age bias resume', 'mature worker resume'],
    longTailKeywords: ['how to write resume over 50', 'resume tips for workers over 60', 'how to avoid age discrimination resume', 'should I put graduation year on resume over 50', 'modern resume for older professional', 'resume for career comeback after 50'],
    faqs: [
      { q: 'Should I put graduation year on resume over 50?', a: 'No. Keep degree + university. Year adds nothing and telegraphs age.' },
      { q: 'How far back should my resume go?', a: '10 to 15 years in detail. Earlier collapses into one-line Earlier Experience block.' },
      { q: 'Should I switch to functional to hide timelines?', a: 'No. Functional gets downweighted by ATS and flagged by recruiters.' },
      { q: 'Does this apply at 45 to 50?', a: 'Most of it. Compression gets more aggressive above 55.' },
      { q: 'Is this dishonest?', a: 'No. Editing for relevance; no field fabricated; nothing required left off.' },
    ],
  },
  'cover-letter-software-engineer': {
    slug: 'cover-letter-software-engineer',
    title: 'Cover Letter Examples for Software Engineers (2026)',
    description: '5 worked cover letter examples for software engineers (fresher, FAANG, startup, stack-switch, backend-to-fullstack). 4-part structure, adaptation rules, common mistakes.',
    category: 'Interviews & Cover Letters',
    categorySlug: 'interviews-cover-letters',
    datePublished: '2026-05-19',
    dateModified: '2026-05-19',
    publishAt: '2026-05-19T04:56:00Z',
    primaryKeyword: 'software engineer cover letter',
    secondaryKeywords: ['cover letter software developer', 'engineering cover letter', 'developer cover letter template', 'cover letter for tech jobs'],
    longTailKeywords: ['cover letter for software engineer fresher', 'FAANG cover letter example', 'cover letter for startup software engineer', 'backend to fullstack cover letter', 'software engineer cover letter no experience', 'how to write cover letter for tech job'],
    faqs: [
      { q: 'Do FAANG companies actually read cover letters?', a: 'Mostly no. The application form rarely has a field for one. Exception: internal referrals and staff-plus roles where recruiters forward a packet to the hiring manager.' },
      { q: 'How long should a software engineer cover letter be?', a: 'Between 280 and 380 words. One page with white space.' },
      { q: 'Do I need a cover letter for a startup?', a: 'Yes, for anything below Series C. Founders read cover letters carefully.' },
      { q: 'Can I use AI to draft my cover letter?', a: 'Use it to outline, not to draft. AI drafts read like AI drafts to anyone who has read 50 letters in a week.' },
      { q: 'What if I have no work experience?', a: 'Replace the proof paragraph with projects, open-source patches, coursework with measurable outcomes.' },
    ],
  },
  'greenhouse-ats-tips': {
    slug: 'greenhouse-ats-tips',
    title: 'Greenhouse ATS: How to Stand Out in Startup Hiring (2026)',
    description: 'Greenhouse runs hiring at Airbnb, Stripe, Figma, Notion, and most YC startups. 8 tactical tips, Greenhouse vs Workday, scorecard flow, and auto-reject rules.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-05-21',
    dateModified: '2026-05-21',
    publishAt: '2026-05-21T05:42:00Z',
    primaryKeyword: 'Greenhouse ATS',
    secondaryKeywords: ['Greenhouse applicant tracking', 'Greenhouse resume tips', 'Greenhouse startup hiring', 'Greenhouse recruit'],
    longTailKeywords: ['how does Greenhouse ATS work', 'Greenhouse vs Workday', 'startups using Greenhouse', 'how to pass Greenhouse ATS', 'Greenhouse scorecard interview', 'Greenhouse resume format'],
    faqs: [
      { q: 'How do I know if a company uses Greenhouse?', a: 'Apply URL contains /boards/ or redirects to boards.greenhouse.io.' },
      { q: 'Does Greenhouse auto-reject based on keywords?', a: 'No. Auto-reject uses knockout questions (years experience, work authorisation, location).' },
      { q: 'What format should my resume be?', a: 'PDF, single column, clean sans-serif. Greenhouse shows file inline, so human legibility matters more than parser-safety.' },
      { q: 'Can I edit my application after submitting?', a: 'Usually no. Email the recruiter directly.' },
    ],
  },
  'resume-for-promotion': {
    slug: 'resume-for-promotion',
    title: 'Resume for a Promotion: Internal Transfer Playbook (2026)',
    description: 'Internal promotions ride on a Promotion Case Doc, not a resume. Full framework, 5 examples across IC, Staff, Manager, lateral, cross-functional, plus timing.',
    category: 'Career Growth & Mobility',
    categorySlug: 'career-growth',
    datePublished: '2026-05-24',
    dateModified: '2026-05-24',
    publishAt: '2026-05-24T05:23:00Z',
    primaryKeyword: 'resume for internal promotion',
    secondaryKeywords: ['promotion resume', 'internal transfer resume', 'promotion case document', 'promotion self-assessment'],
    longTailKeywords: ['how to write resume for internal promotion', 'promotion resume template', 'internal transfer cover letter', 'how to ask for promotion', 'promotion self-assessment template', 'internal move resume'],
    faqs: [
      { q: 'Do I need a resume for an internal promotion?', a: 'No. Use a Promotion Case Doc instead.' },
      { q: 'How long should the Promotion Case Doc be?', a: '2 to 4 pages for IC and Senior; 4 to 6 pages for Staff, Principal, and EM.' },
      { q: 'What if my manager is neutral on my promotion?', a: 'Neutral is not sponsorship. Ask directly if they are sponsoring; fix sponsorship before writing the packet.' },
      { q: 'What if I get rejected?', a: 'Ask for calibration-level feedback in writing. Gap list becomes your next 6-month plan.' },
    ],
  },
  'salary-negotiation-scripts': {
    slug: 'salary-negotiation-scripts',
    title: 'Salary Negotiation Scripts for Software Engineers (India + US)',
    description: 'Verbatim scripts for 6 real negotiation scenarios across India and US markets. Research stack, recruiter counter-moves, email template.',
    category: 'Salary & Negotiation',
    categorySlug: 'salary-negotiation',
    datePublished: '2026-06-09',
    dateModified: '2026-06-09',
    publishAt: '2026-06-09T05:33:00Z',
    primaryKeyword: 'salary negotiation script',
    secondaryKeywords: ['salary negotiation software engineer', 'counter offer script', 'how to negotiate salary', 'tech salary negotiation'],
    longTailKeywords: ['salary negotiation script for software engineer', 'how to counter a lowball offer', 'salary negotiation email template', 'how much to counter a job offer', 'salary negotiation India software engineer', 'FAANG salary negotiation'],
    faqs: [
      { q: 'How much can I realistically negotiate?', a: '8 to 20 percent on a typical offer. 25 to 40 percent with a competing offer on a lowballed first offer.' },
      { q: 'Should I negotiate a fresher offer?', a: 'Yes, expect 5 to 10 percent. Focus on sign-on, joining date, level.' },
      { q: 'How do I negotiate with only one offer?', a: 'Use data, not leverage. Triangulate 75th percentile from three sources.' },
      { q: 'Is FAANG negotiation different?', a: 'Yes. Equity and sign-on are big levers; level adjustment can unlock 30 percent more.' },
    ],
  },
  'resume-not-getting-callbacks': {
    slug: 'resume-not-getting-callbacks',
    title: 'Why Your Resume Is Not Getting Callbacks: 15 Reasons (2026)',
    description: 'The callback funnel math, 15 specific reasons grouped by content, format, fit, targeting, and timing. Plus a 5-minute self-audit.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-06-11',
    dateModified: '2026-06-11',
    publishAt: '2026-06-11T04:47:00Z',
    primaryKeyword: 'resume not getting callbacks',
    secondaryKeywords: ['why no callbacks resume', 'resume no response', 'resume not working', 'improve resume callback rate'],
    longTailKeywords: ['why is my resume not getting callbacks', 'how many applications before callback', 'resume rejection reasons', 'how to improve resume callback rate', 'resume getting rejected by ATS', 'applied to 100 jobs no response'],
    faqs: [
      { q: 'How many applications before I should expect a callback?', a: 'On a strong targeted resume, first callback by application 10 to 15. Past 30 with nothing, audit the resume.' },
      { q: 'Is 100 applications normal for no offer?', a: '100 to 1 offer is normal. 100 with zero callbacks is a diagnostic signal.' },
      { q: 'Should I follow up on applications?', a: 'Yes, with a specific recruiter or hiring manager, 5 to 7 days after applying.' },
      { q: 'Is it the resume or the market?', a: 'If peers at similar companies are landing callbacks, it is the resume.' },
    ],
  },
  'military-civilian-resume': {
    slug: 'military-civilian-resume',
    title: 'Military to Civilian Resume: India + US Guide (2026)',
    description: 'Translate MOS, rank, and deployments into civilian language. Transferable skills matrix, 6 certifications, 3 worked summaries, veteran hiring programs.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-06-14',
    dateModified: '2026-06-14',
    publishAt: '2026-06-14T06:01:00Z',
    primaryKeyword: 'military to civilian resume',
    secondaryKeywords: ['veteran resume', 'military transition resume', 'ex-military resume', 'armed forces civilian resume'],
    longTailKeywords: ['how to convert military resume to civilian', 'military resume translator', 'veteran resume template', 'ex-military resume India', 'veteran hiring programs', 'military officer to civilian job'],
    faqs: [
      { q: 'Should I include rank on my civilian resume?', a: 'Yes, alongside the civilian translation. Major (equivalent to Senior Operations Manager).' },
      { q: 'How far back should my military experience go?', a: 'Full history under 15 years of service; over 15, detail last 10 and summarise earlier.' },
      { q: 'What if my MOS has no civilian equivalent?', a: 'Translate underlying skills: leadership, planning, logistics, training.' },
      { q: 'Is a security clearance valuable?', a: 'In the US, active Secret or Top Secret is a 10 to 20 percent premium for defence + finance roles.' },
    ],
  },
  'chatgpt-prompts-resume': {
    slug: 'chatgpt-prompts-resume',
    title: '50 ChatGPT Prompts for Resume Writing (2026)',
    description: '50 copy-paste ChatGPT prompts for resume summaries, bullet rewrites, skills, cover letters, JD matching, tailoring. 6 categories plus 5 tips for better output.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-06-16',
    dateModified: '2026-06-16',
    publishAt: '2026-06-16T04:52:00Z',
    primaryKeyword: 'ChatGPT prompts for resume',
    secondaryKeywords: ['AI resume prompts', 'ChatGPT resume writing', 'resume writing prompts', 'ChatGPT for job search'],
    longTailKeywords: ['best ChatGPT prompts for resume', 'ChatGPT prompts to rewrite resume bullets', 'ChatGPT prompt to tailor resume to JD', 'ChatGPT cover letter prompts', 'ChatGPT prompts for software engineer resume', 'free AI resume prompts'],
    faqs: [
      { q: 'Will recruiters know my resume was written with ChatGPT?', a: 'If you paste output verbatim, yes. Generic verbs, rule-of-three lists, and zero specificity are the tells.' },
      { q: 'Is it OK if ChatGPT invents metrics?', a: 'No. Invented numbers are resume fraud. Mark placeholders and replace with real numbers before submitting.' },
      { q: 'Should I paste my entire resume into ChatGPT?', a: 'Redact employer names and personal identifiers first.' },
      { q: 'Does ChatGPT hurt ATS scoring?', a: 'No. ATS scores keywords and format, not authorship.' },
      { q: 'Best prompt on the list?', a: 'The JD scoring prompt. Surfaces concrete gaps between your resume and a target job in one pass.' },
    ],
  },
  'gpa-on-resume': {
    slug: 'gpa-on-resume',
    title: 'Should You Put GPA on a Resume? (2026 Guide)',
    description: 'When to include GPA (3.5+ / CGPA 8.0+, recent grad, analytical roles) and when to skip. Format rules, CGPA vs percentage, grad school vs industry.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-06-18',
    dateModified: '2026-06-18',
    publishAt: '2026-06-18T05:48:00Z',
    primaryKeyword: 'should I put GPA on resume',
    secondaryKeywords: ['GPA on resume', 'CGPA on resume', 'resume GPA format', 'when to remove GPA resume'],
    longTailKeywords: ['should I put GPA on resume if low', 'when to remove GPA from resume', 'CGPA on resume India', 'GPA on resume for experienced', 'how to list GPA on resume', 'GPA vs CGPA resume'],
    faqs: [
      { q: 'Is it lying to omit GPA?', a: 'No. GPA is optional. Omission is not deception. Answer honestly if asked in interview.' },
      { q: 'Should I round GPA up?', a: 'No. 3.84 stays 3.84. Rounding is dishonest and discoverable if a transcript is requested.' },
      { q: 'Do US employers understand CGPA?', a: 'Most do. Include scale (CGPA: 8.7/10). Percentage is the safe conversion.' },
      { q: 'Should I include Class 10 and 12 percentages?', a: 'Yes if fresher. No once you have 2+ years of work experience.' },
    ],
  },
  'freelance-resume': {
    slug: 'freelance-resume',
    title: 'Freelance Resume: How to Sell Self-Employment (2026)',
    description: 'How to frame freelance and contract work so it reads like a career, not a gap. Portfolio-as-Proof pattern, NDA workarounds, 4 worked summaries.',
    category: 'Freelance & Contract',
    categorySlug: 'freelance-contract',
    datePublished: '2026-06-21',
    dateModified: '2026-06-21',
    publishAt: '2026-06-21T05:19:00Z',
    primaryKeyword: 'freelance resume',
    secondaryKeywords: ['freelance resume template', 'freelance to fulltime resume', 'contractor resume', 'self-employed resume'],
    longTailKeywords: ['how to write freelance resume', 'freelance resume examples', 'freelance to fulltime resume', 'self-employed resume format', 'freelance designer resume', 'freelance developer resume'],
    faqs: [
      { q: 'Should I list every client?', a: 'No. Curate to 3 to 5 featured engagements.' },
      { q: 'What job title should I use?', a: 'Pick one (Freelance [Discipline], Independent [Discipline] Consultant) and use consistently.' },
      { q: 'How do I quantify outcomes when clients do not share data?', a: 'Proxy metrics: hours saved, team size affected, users, release frequency.' },
      { q: 'How long should a freelance resume be?', a: 'One page under 5 years; two pages over 5 years or with prior FTE history.' },
      { q: 'Will a freelance resume pass ATS?', a: 'Yes, formatted as single-employer block with nested engagements.' },
    ],
  },
  'claude-prompts-job-search': {
    slug: 'claude-prompts-job-search',
    title: '30 Claude Prompts for Job Search (2026)',
    description: '30 ready-to-paste Claude prompts across resume polish, cover letters, mock interviews, negotiation, LinkedIn, and outreach. Plus context-passing tips and honest Claude vs ChatGPT notes.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-06-23',
    dateModified: '2026-06-23',
    publishAt: '2026-06-23T05:06:00Z',
    primaryKeyword: 'Claude prompts for job search',
    secondaryKeywords: ['Claude AI resume', 'Claude prompts resume', 'Claude for cover letter', 'Anthropic Claude job search'],
    longTailKeywords: ['best Claude prompts for resume', 'Claude vs ChatGPT for resume', 'Claude prompt to rewrite cover letter', 'Claude mock interview prompts', 'Claude prompts LinkedIn optimization', 'how to use Claude for job hunting'],
    faqs: [
      { q: 'Do I need paid Claude for these prompts?', a: 'No. Free tier handles all 30; heavy mock-interview sessions may hit a daily limit.' },
      { q: 'How do I stop Claude from inventing metrics?', a: 'Add: Do not fabricate numbers. If a claim needs data I have not provided, ask me one question.' },
      { q: 'Is Claude better than ChatGPT for resumes?', a: 'For voice-heavy work (cover letters, summaries), Claude holds tone better. For research-heavy, ChatGPT with browsing is faster.' },
      { q: 'How do I make Claude sound less like AI?', a: 'Short sentences, concrete nouns, no hedges; provide a 3-sentence sample of your real writing as voice anchor.' },
    ],
  },
  'resume-headline': {
    slug: 'resume-headline',
    title: 'How to Write a Resume Headline That Gets Clicks (2026)',
    description: 'The 4-part formula (Role + Specialty + Domain + Metric), 15 headline examples by role, resume vs LinkedIn headline, and the 6 mistakes that kill it.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-06-25',
    dateModified: '2026-06-25',
    publishAt: '2026-06-25T05:58:00Z',
    primaryKeyword: 'resume headline',
    secondaryKeywords: ['resume headline examples', 'resume headline for freshers', 'resume title', 'professional headline resume'],
    longTailKeywords: ['resume headline examples for software engineer', 'resume headline for experienced', 'resume headline vs summary', 'resume headline for freshers', 'resume headline formula', 'catchy resume headlines'],
    faqs: [
      { q: 'Do I need a headline if I have a summary?', a: 'Yes. Different jobs. Headline = one-second scan; summary = 10-second read.' },
      { q: 'Should freshers use a headline?', a: 'Yes. Lead with degree + stack + one shipped project.' },
      { q: 'How long should a resume headline be?', a: '80 to 110 characters, one line at body font size.' },
      { q: 'Where does the headline sit?', a: 'Directly below your name, above or beside contact info, 11 to 13 pt.' },
    ],
  },
  'phd-to-industry-resume': {
    slug: 'phd-to-industry-resume',
    title: 'PhD to Industry Resume: The Conversion Guide (2026)',
    description: 'The 3-page CV to 1-page resume compression, translating publications and teaching into industry impact, and 3 worked summaries.',
    category: 'Career Transitions',
    categorySlug: 'career-transitions',
    datePublished: '2026-06-28',
    dateModified: '2026-06-28',
    publishAt: '2026-06-28T04:44:00Z',
    primaryKeyword: 'PhD resume industry',
    secondaryKeywords: ['academic to industry resume', 'PhD to industry transition', 'CV vs resume PhD', 'post-doc resume'],
    longTailKeywords: ['how to convert academic CV to resume', 'PhD resume template industry', 'post-doc to industry resume', 'PhD to data science resume', 'explaining academic background on resume', 'leaving academia for industry'],
    faqs: [
      { q: 'Should I keep publications on my industry resume?', a: 'Yes, compressed. 3 to 5 most-cited at the bottom; full list via Google Scholar link.' },
      { q: 'Is 1 page realistic for a PhD with 10 years of research?', a: 'For R&D roles, 2 pages. For non-research industry roles, aim for 1 page.' },
      { q: 'Should I mention I am transitioning?', a: 'In the summary, one line. Recruiters appreciate clarity.' },
      { q: 'Do I list citation counts?', a: 'For research roles, yes. For PM or consulting, no.' },
    ],
  },
  'ai-rewrite-bullets': {
    slug: 'ai-rewrite-bullets',
    title: 'How to Rewrite Resume Bullets with AI (Before / After Library)',
    description: 'The exact rewrite prompt, 20 before / after pairs across 6 roles, and the 6 hallucination patterns to catch before you hit submit.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-06-30',
    dateModified: '2026-06-30',
    publishAt: '2026-06-30T05:27:00Z',
    primaryKeyword: 'rewrite resume bullet points',
    secondaryKeywords: ['AI resume bullets', 'resume bullet rewriter', 'AI bullet point rewriter', 'improve resume bullets'],
    longTailKeywords: ['how to rewrite resume bullets with AI', 'before and after resume bullets', 'resume bullet point examples', 'AI prompt to rewrite resume bullets', 'weak to strong resume bullets', 'resume bullet improvement'],
    faqs: [
      { q: 'Which AI model gives the best rewrites?', a: 'Claude, ChatGPT-5, Gemini 2 are all close. Claude asks for missing numbers instead of inventing.' },
      { q: 'Should I let AI add metrics it guessed?', a: 'No. Any number you did not supply should be deleted or replaced with one you can defend.' },
      { q: 'How long should each bullet be?', a: '18 to 22 words.' },
      { q: 'Do I need to disclose AI assistance?', a: 'Not on the resume. You own the numbers; AI only polished the sentence.' },
    ],
  },
  'leadership-on-resume': {
    slug: 'leadership-on-resume',
    title: 'How to Describe Leadership on a Resume Without a Title (2026)',
    description: '10 phrases, 8 worked bullets, and the mentorship plus cross-functional framing that show you can step up without Manager on your name tag.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-07-02',
    dateModified: '2026-07-02',
    publishAt: '2026-07-02T04:41:00Z',
    primaryKeyword: 'leadership on resume',
    secondaryKeywords: ['describe leadership on resume', 'IC to manager resume', 'leadership bullets', 'informal leadership resume'],
    longTailKeywords: ['how to describe leadership without title', 'leadership skills on resume examples', 'IC to manager resume transition', 'mentorship on resume', 'leading without authority resume', 'leadership accomplishments resume'],
    faqs: [
      { q: 'Can I use the title Team Lead if it was informal?', a: 'No. Use official title and describe lead responsibilities in bullets.' },
      { q: 'Should I add a Leadership section?', a: 'Only if you cannot weave it into existing bullets.' },
      { q: 'How much leadership framing is too much?', a: '2 to 4 leadership bullets per role; over 40 percent and technical content suffers.' },
      { q: 'Does Tech Lead count without direct reports?', a: 'Yes. Name the team size and project scope.' },
    ],
  },
  'resume-international-jobs': {
    slug: 'resume-international-jobs',
    title: 'Resume for International Jobs: H1B, UK, Canada (2026)',
    description: 'Regional conventions across 6 markets, exactly how to state visa context, and the timezone note that makes remote applications credible.',
    category: 'Remote Work & Global Jobs',
    categorySlug: 'remote-global',
    datePublished: '2026-07-05',
    dateModified: '2026-07-05',
    publishAt: '2026-07-05T06:02:00Z',
    primaryKeyword: 'resume for international jobs',
    secondaryKeywords: ['H1B resume', 'UK resume', 'Canada PR resume', 'international resume format'],
    longTailKeywords: ['resume for H1B applications', 'UK skilled worker visa resume', 'Canada PR resume format', 'resume for Germany jobs', 'international job resume template', 'how to mention visa status on resume'],
    faqs: [
      { q: 'Should I keep two resumes, one for India and one for US?', a: 'Yes. Page size, length, date format, visa line all change.' },
      { q: 'Should I hide my India address when applying to US?', a: 'No. Honest location + clear sponsorship line beats faked addresses.' },
      { q: 'Do I need to translate my resume for Germany?', a: 'English acceptable at most tech firms; traditional sectors prefer Lebenslauf.' },
      { q: 'Should I list IELTS / TOEFL?', a: 'Yes for UK / Canada / Australia migration. Skip if you studied in English-medium country.' },
    ],
  },
  'grammarly-resume-review': {
    slug: 'grammarly-resume-review',
    title: 'Grammarly for Resumes: Does It Actually Help? (2026)',
    description: 'What Grammarly catches on a resume, what it misses, 5 situations where it hurts, Free vs Premium, and how it compares to ChatGPT, Claude, Hemingway.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-07-07',
    dateModified: '2026-07-07',
    publishAt: '2026-07-07T05:39:00Z',
    primaryKeyword: 'Grammarly resume',
    secondaryKeywords: ['Grammarly for resume', 'Grammarly premium resume', 'resume proofreading AI', 'grammar check resume'],
    longTailKeywords: ['does Grammarly help for resume', 'Grammarly vs ChatGPT for resume', 'Grammarly premium worth it resume', 'resume grammar checker', 'free resume proofreader', 'Grammarly mistakes on resume'],
    faqs: [
      { q: 'Does Grammarly help for a resume?', a: 'Yes for typos, tense, agreement. No for weak verbs, missing numbers, ATS formatting, JD alignment.' },
      { q: 'Is Grammarly Premium worth it?', a: 'Only if you use Grammarly for broader writing; Premium features add little to bullet writing alone.' },
      { q: 'Grammarly vs ChatGPT?', a: 'Grammarly catches mechanical errors; LLMs restructure weak bullets and tailor to JD. Use both.' },
      { q: 'Should I let Grammarly rewrite bullets?', a: 'No. Grammarly smooths bullets into softer prose. Use for fixes, not rewrites.' },
    ],
  },
  'certifications-on-resume': {
    slug: 'certifications-on-resume',
    title: 'How to List Certifications on a Resume by Field (2026)',
    description: 'What counts as a certification, 6 format fields, top 5 certs for 8 fields, and expired-cert strategy.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-07-09',
    dateModified: '2026-07-09',
    publishAt: '2026-07-09T04:48:00Z',
    primaryKeyword: 'certifications on resume',
    secondaryKeywords: ['how to list certifications resume', 'resume certifications format', 'best certifications for resume', 'certification section resume'],
    longTailKeywords: ['how to list AWS certification on resume', 'PMP certification on resume', 'expired certifications on resume', 'certifications for software engineer resume', 'do certifications matter on resume', 'certifications section resume format'],
    faqs: [
      { q: 'How do I list AWS on a resume?', a: 'Full name, issuer, year, validity, credential ID.' },
      { q: 'Should I list expired certifications?', a: 'Only if recent (under 12 months) or marquee (CFA, CPA, bar).' },
      { q: 'How many certifications is too many?', a: '3 to 6 for most fields; cloud/compliance/finance justify 7 to 10.' },
      { q: 'Do online course completions count?', a: 'Only if proctored exam or graded capstone.' },
    ],
  },
  'board-advisor-resume': {
    slug: 'board-advisor-resume',
    title: 'Resume for a Board Seat or Advisor Role (2026)',
    description: 'How board bios differ from executive resumes, the 3-section structure, governance framing, independence criteria, and 3 worked summaries.',
    category: 'Career Growth & Mobility',
    categorySlug: 'career-growth',
    datePublished: '2026-07-12',
    dateModified: '2026-07-12',
    publishAt: '2026-07-12T05:52:00Z',
    primaryKeyword: 'board member resume',
    secondaryKeywords: ['board seat CV', 'advisor resume', 'non-executive director resume', 'board bio'],
    longTailKeywords: ['how to write resume for board position', 'board bio template', 'advisor role resume', 'non-executive director CV', 'board of directors resume examples', 'first time board member resume'],
    faqs: [
      { q: 'How long should a board bio be?', a: '100 to 150 words on a single page for the narrative bio, plus a 2-page director CV.' },
      { q: 'Should I use third-person in a board bio?', a: 'Yes. Proxy-filing convention: third-person, factual, governance-forward.' },
      { q: 'What if I have no prior board experience?', a: 'Frame internal committee chairs, non-profit governance, 1 to 2 advisory agreements.' },
      { q: 'How to get the first board seat?', a: 'Non-profit boards, industry associations, PE/VC portfolio observer seats.' },
    ],
  },
  'icims-taleo-resume': {
    slug: 'icims-taleo-resume',
    title: 'iCIMS and Taleo: Legacy ATS Rules That Still Apply (2026)',
    description: 'iCIMS and Taleo power hiring at hundreds of Fortune 500 companies. 8 rules, platform differences, and mistakes that drop your match score.',
    category: 'ATS & Keywords',
    categorySlug: 'ats-keywords',
    datePublished: '2026-07-14',
    dateModified: '2026-07-14',
    publishAt: '2026-07-14T04:53:00Z',
    primaryKeyword: 'iCIMS resume tips',
    secondaryKeywords: ['Taleo resume', 'legacy ATS', 'iCIMS ATS tips', 'Taleo ATS parsing'],
    longTailKeywords: ['how to pass iCIMS ATS', 'Taleo resume parsing', 'iCIMS vs Taleo', 'companies that use iCIMS', 'Taleo resume format', 'legacy ATS resume tips'],
    faqs: [
      { q: 'PDF or DOCX for Taleo?', a: 'DOCX. Taleo has historically mis-parsed PDFs, especially LaTeX / InDesign exports.' },
      { q: 'How to tell if a company uses iCIMS or Taleo?', a: 'URL: jobs.icims.com = iCIMS; taleo.net = Taleo.' },
      { q: 'Literal or stemmed keyword match?', a: 'iCIMS stemmed. Taleo 17+ stemmed; older literal-match.' },
      { q: 'Do these systems score my application?', a: 'Yes. Above 70 percent typically surfaces in first screen.' },
    ],
  },
  'side-projects-on-resume': {
    slug: 'side-projects-on-resume',
    title: 'How to Show Side Projects on Your Resume (2026)',
    description: 'Which side projects belong on a resume, where to place by career stage, how to write the bullet, and the 6 mistakes that turn projects into filler.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-07-16',
    dateModified: '2026-07-16',
    publishAt: '2026-07-16T05:41:00Z',
    primaryKeyword: 'side projects on resume',
    secondaryKeywords: ['personal projects resume', 'side project bullets', 'resume side projects', 'GitHub projects resume'],
    longTailKeywords: ['how to list side projects on resume', 'side projects for freshers resume', 'open source contributions on resume', 'hackathon projects on resume', 'side project examples resume', 'resume project section format'],
    faqs: [
      { q: 'How many side projects?', a: 'Freshers 4 to 6; early-career 2 to 3; mid-career 1 to 2; senior skip.' },
      { q: 'Do open source contributions count?', a: 'Yes, if merged and non-trivial.' },
      { q: 'Should I include tutorial clones?', a: 'No. Signals you followed instructions.' },
      { q: 'What if my project has no users?', a: 'Show the work: commits, tests, live demo, video.' },
    ],
  },
  'naukri-vs-linkedin-india': {
    slug: 'naukri-vs-linkedin-india',
    title: 'Naukri vs LinkedIn vs Instahyre: Indian Job Boards Compared (2026)',
    description: 'Naukri is volume. LinkedIn is narrative. Instahyre is curation. Which platform fits your stage, and the tactics that raise callback rate.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-07-19',
    dateModified: '2026-07-19',
    publishAt: '2026-07-19T05:17:00Z',
    primaryKeyword: 'Naukri vs LinkedIn',
    secondaryKeywords: ['Indian job boards', 'LinkedIn India jobs', 'Instahyre India', 'best job site India'],
    longTailKeywords: ['Naukri vs LinkedIn for jobs India', 'best job portal India 2026', 'Instahyre vs Naukri', 'where to find tech jobs India', 'which job site is best in India', 'LinkedIn or Naukri which is better'],
    faqs: [
      { q: 'Better for freshers: Naukri or LinkedIn?', a: 'Naukri volume, LinkedIn networking. Use both, Naukri primary.' },
      { q: 'Is Instahyre only for tech?', a: 'Mostly. Product / data / design / tech dominate.' },
      { q: 'Do I need LinkedIn Premium in India?', a: 'Not year-round. 1-month trial during active hunt pays for itself.' },
      { q: 'Are referrals really better?', a: 'Yes. 4 to 5x higher interview rates in Indian tech hiring.' },
    ],
  },
  'one-column-vs-two-column-resume': {
    slug: 'one-column-vs-two-column-resume',
    title: '1-Column vs 2-Column Resume: Which Is Better for ATS? (2026)',
    description: 'Direct answer based on actual ATS parsing across Workday, Taleo, Greenhouse, Lever, iCIMS, SAP SuccessFactors. Plus cases where 2-column is OK.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-07-28',
    dateModified: '2026-07-28',
    publishAt: '2026-07-28T04:51:00Z',
    primaryKeyword: '2 column resume',
    secondaryKeywords: ['1 column vs 2 column resume', 'resume columns', 'two column resume ATS', 'single column resume'],
    longTailKeywords: ['is 2 column resume good', 'does ATS read 2 column resumes', 'best resume column layout', 'single vs double column resume', '2 column resume template', 'resume column format for ATS'],
    faqs: [
      { q: 'Does ATS read 2 column resumes in 2026?', a: 'Greenhouse / Lever parse reasonably. Workday / Taleo / iCIMS / SAP scramble. Default 1-column.' },
      { q: 'Is 2 column good for freshers?', a: 'No. Campus drives run on Workday or SuccessFactors.' },
      { q: 'Can I use 2 columns on a 2-page resume?', a: 'Same answer. Twice the parse risk.' },
      { q: 'What about Canva 2-column templates?', a: 'Most use text boxes; invisible to many ATS.' },
    ],
  },
  'iit-placement-resume': {
    slug: 'iit-placement-resume',
    title: 'IIT / NIT Placement Resume Template (2026)',
    description: 'Section order, bullet depth, branch-specific tailoring that clears Day 1 shortlists. SPO-compliant one page, CSE + Mechanical examples, 7 mistakes.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-07-30',
    dateModified: '2026-07-30',
    publishAt: '2026-07-30T05:44:00Z',
    primaryKeyword: 'IIT placement resume',
    secondaryKeywords: ['NIT placement resume', 'IIT resume template', 'CS branch IIT resume', 'IIT Bombay placement'],
    longTailKeywords: ['IIT placement resume format', 'IIT CSE placement resume', 'NIT placement resume template', 'IIT internship resume', 'IIT final year placement resume', 'best resume for IIT placements'],
    faqs: [
      { q: 'Can IIT placement resume be 2 pages?', a: 'No. SPO rules mandate 1 page.' },
      { q: 'Include CGPA if below 7.5?', a: 'Yes. SPO verifies transcripts. Balance with strong projects.' },
      { q: 'Do I need a photo?', a: 'No. SPO templates do not include a photo.' },
      { q: 'How many projects?', a: '3 to 5 with real depth.' },
    ],
  },
  'jobscan-alternatives': {
    slug: 'jobscan-alternatives',
    title: 'Jobscan Alternatives: What Actually Works in 2026',
    description: 'Honest comparison of 6 Jobscan alternatives across price, keyword depth, ATS parse simulation, suggestion quality. Plus red flags that make scores meaningless.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-08-02',
    dateModified: '2026-08-02',
    publishAt: '2026-08-02T05:14:00Z',
    primaryKeyword: 'Jobscan alternative',
    secondaryKeywords: ['free Jobscan alternative', 'ATS resume checker', 'Jobscan vs', 'resume scanner'],
    longTailKeywords: ['best Jobscan alternative', 'free ATS checker', 'Jobscan vs Resume Worded', 'ATS scanner free', 'resume score checker', 'free resume ATS checker tool'],
    faqs: [
      { q: 'Best free Jobscan alternative?', a: 'Enhancv Checker and Teal both free-scan without hard caps.' },
      { q: 'Resume Worded better than Jobscan?', a: 'Different focus. RW for LinkedIn scoring; Jobscan for JD-keyword matching.' },
      { q: 'Any simulate Workday?', a: 'None 1:1. Jobscan + Teal closest.' },
      { q: 'Need to pay?', a: 'No. Free tiers + clean structure cover 80 percent.' },
    ],
  },
  'resume-objective-vs-summary': {
    slug: 'resume-objective-vs-summary',
    title: 'Resume Objective vs Summary: When to Use Each (2026)',
    description: 'Objective vs summary on a 2026 resume: when to use each, 8 weak-vs-strong examples, 6 mistakes, and the 4-part summary formula recruiters reward.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-07-21',
    dateModified: '2026-07-21',
    publishAt: '2026-07-21T04:45:00Z',
    primaryKeyword: 'resume objective vs summary',
    secondaryKeywords: ['resume objective', 'resume summary', 'when to use objective', 'career objective'],
    longTailKeywords: ['objective vs summary on resume', 'should I use objective or summary', 'resume objective for freshers', 'when to include career objective', 'resume summary for experienced', 'objective vs professional summary'],
    faqs: [
      { q: 'Can I skip both?', a: 'Not ideal. Top block is first thing a recruiter reads. Even 2-sentence summary lifts callback rate.' },
      { q: 'Is career objective outdated?', a: 'Generic objectives are. Specific forward-looking objectives are still right for freshers, career changers, returnships.' },
      { q: 'Should freshers always use objective?', a: 'Usually. Unless fresher has 2+ shipped internships with strong numbers.' },
      { q: 'How long should the summary be?', a: '40 to 90 words. Three to four sentences.' },
      { q: 'Does ATS care?', a: 'No. ATS parses text regardless of label.' },
    ],
  },
  'hobbies-on-resume': {
    slug: 'hobbies-on-resume',
    title: 'Resume Hobbies and Interests: When They Help (2026)',
    description: 'Hobbies help in 5 clear situations and hurt in 5 others. 2026 rules, 30 high-signal hobbies, what to skip, and the 3-line format that works.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-07-23',
    dateModified: '2026-07-23',
    publishAt: '2026-07-23T05:56:00Z',
    primaryKeyword: 'hobbies on resume',
    secondaryKeywords: ['interests on resume', 'hobbies to list on resume', 'personal interests resume', 'hobbies section resume'],
    longTailKeywords: ['should I put hobbies on resume', 'best hobbies to list on resume', 'hobbies for software engineer resume', 'hobbies that impress recruiters', 'list of hobbies for resume', 'creative hobbies for resume'],
    faqs: [
      { q: 'Will recruiters read hobbies?', a: 'Yes, but only if they already decided to read you in full.' },
      { q: 'Should I list hobbies on SWE resume?', a: 'If technical (OSS, competitive programming, hackathons), yes. If generic, skip.' },
      { q: 'How many hobbies?', a: '3 to 5.' },
      { q: 'Can hobbies hurt me?', a: 'Yes. Polarising hobbies can trigger bias-driven screen-outs.' },
      { q: 'Do Indian recruiters care?', a: 'Campus recruiters at Tier-1 still glance; laterals above 5 yrs rarely.' },
    ],
  },
  'resume-indian-govt-jobs': {
    slug: 'resume-indian-govt-jobs',
    title: 'Resume for Indian Government Jobs: UPSC, SSC, Railways (2026)',
    description: 'Government resume playbook for UPSC DAF, SSC, RRB, PSU, Banking, Defence. 10 mandatory sections, format spec, and 8 rejection-causing mistakes.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-07-26',
    dateModified: '2026-07-26',
    publishAt: '2026-07-26T05:22:00Z',
    primaryKeyword: 'government job resume',
    secondaryKeywords: ['UPSC resume', 'SSC resume', 'government job India', 'PSU resume'],
    longTailKeywords: ['resume for UPSC interview', 'resume for SSC interview', 'resume format for government jobs', 'PSU resume format', 'government job resume template India', 'resume for bank PO interview'],
    faqs: [
      { q: 'Can I use Canva template?', a: 'No. Panels penalise non-standard layouts. Plain single-column, conservative fonts.' },
      { q: 'Is 2-page acceptable for UPSC DAF?', a: 'DAF is as long as needed, not capped.' },
      { q: 'Attach photo and signature?', a: 'Yes. Passport-size, white background, top-right, signed. Missing = rejection.' },
      { q: 'Multiple UPSC/SSC attempts?', a: 'List honestly. Shows persistence if trend upward.' },
      { q: 'Are NCC / NSS important?', a: 'Very. NCC B/C certificate carries concrete weight.' },
    ],
  },
  'job-hopping-resume': {
    slug: 'job-hopping-resume',
    title: 'How to Explain Job Hopping on a Resume (2026)',
    description: 'Short stints are routine in 2026 if you frame them. Exact line edits, summary hooks, and interview scripts that keep job hopping from killing the callback.',
    category: 'Resume Writing',
    categorySlug: 'resume-writing',
    datePublished: '2026-08-04',
    dateModified: '2026-08-04',
    publishAt: '2026-08-04T04:58:00Z',
    primaryKeyword: 'job hopping resume',
    secondaryKeywords: ['explain job hopping', 'short stints resume', 'multiple jobs resume', 'job hopper resume'],
    longTailKeywords: ['how to explain job hopping in interview', 'resume with multiple short jobs', 'how to hide job hopping on resume', 'reasons for job hopping resume', 'job hopping how many jobs is too many', 'short tenure resume format'],
    faqs: [
      { q: 'How many short jobs is too many?', a: 'Two under 18 months back to back reads as pattern. Three or more needs cover letter + rehearsed script.' },
      { q: 'Hide a short stint by leaving it off?', a: 'Only if under 3 months, no reference produced, no gap created.' },
      { q: 'Use years only instead of months?', a: 'Yes. Standard tactic. Be ready to provide exact dates if asked.' },
      { q: 'Contract roles count as hopping?', a: 'Not if labelled. Add (Contract, 8 months) or (Fixed-term).' },
      { q: 'Does ATS flag short tenures?', a: 'No. ATS parses keywords + years, not tenure patterns.' },
    ],
  },
  'indian-unicorn-interview': {
    slug: 'indian-unicorn-interview',
    title: 'Razorpay, PhonePe, Swiggy Interview Prep (2026)',
    description: 'Round-by-round breakdown of interview loops at India 3 most active hiring unicorns. Stack expectations, pay bands, and the resume tactics that land the OA invite.',
    category: 'India Hiring',
    categorySlug: 'india-hiring',
    datePublished: '2026-08-06',
    dateModified: '2026-08-06',
    publishAt: '2026-08-06T05:37:00Z',
    primaryKeyword: 'Razorpay interview',
    secondaryKeywords: ['PhonePe interview', 'Swiggy interview', 'Indian unicorn interview', 'Flipkart interview prep'],
    longTailKeywords: ['Razorpay interview process software engineer', 'PhonePe interview questions', 'Swiggy SDE interview prep', 'Indian unicorn companies interview process', 'fintech interview questions India', 'product company interview India'],
    faqs: [
      { q: 'Total interview loop duration?', a: 'Razorpay 2-3 weeks. PhonePe 3-4 weeks. Swiggy 2-3 weeks.' },
      { q: 'How many LeetCode?', a: 'Quality over quantity. 150 to 200 solved cleanly beats 500 with hints.' },
      { q: 'Do these hire freshers directly?', a: 'Yes. Razorpay RACE, PhonePe campus, Swiggy Step-Up.' },
      { q: 'Is referral necessary?', a: 'Not necessary but helpful. Skips keyword filter.' },
      { q: 'Easiest to crack?', a: 'Razorpay + Zomato rated easier; PhonePe + Flipkart harder.' },
    ],
  },
  'notion-resume-template': {
    slug: 'notion-resume-template',
    title: 'Notion Resume Template: Free Portfolio Setup (2026)',
    description: 'A Notion page is a great public portfolio and a terrible application PDF. The 8 blocks, 7-step setup, and why you still need a PDF for formal submissions.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-08-09',
    dateModified: '2026-08-09',
    publishAt: '2026-08-09T05:09:00Z',
    primaryKeyword: 'Notion resume template',
    secondaryKeywords: ['Notion portfolio', 'free Notion resume', 'Notion CV template', 'resume on Notion'],
    longTailKeywords: ['free Notion resume template', 'Notion resume portfolio template', 'how to make resume in Notion', 'Notion resume for designers', 'Notion portfolio for developers', 'Notion resume template free download'],
    faqs: [
      { q: 'Can I submit Notion resume to ATS?', a: 'No. ATS expects PDF or DOCX. Build real PDF and link Notion URL inside.' },
      { q: 'Is Notion resume free?', a: 'Yes on notion.site. Custom domain via Super.so ~12 USD/mo.' },
      { q: 'Does Notion work for non-tech?', a: 'Yes for creative + product. Less so for finance, legal, traditional corporate.' },
      { q: 'Can I password-protect?', a: 'Not on free tier. Notion Business plans support password-protected public pages.' },
      { q: 'Will recruiters click Notion link?', a: 'Yes in tech. Use vanity URL yourname.notion.site.' },
    ],
  },
  'salary-hike-india': {
    slug: 'salary-hike-india',
    title: 'How to Ask for a Salary Hike in India (2026): Data + Scripts',
    description: 'Market data for 7 industry bands, a 5-step formula to compute your ask, 6 word-for-word appraisal scripts, and the 7 mistakes that turn a strong case into a weak ask.',
    category: 'Salary & Negotiation',
    categorySlug: 'salary-negotiation',
    datePublished: '2026-08-11',
    dateModified: '2026-08-11',
    publishAt: '2026-08-11T04:36:00Z',
    primaryKeyword: 'how to ask for hike',
    secondaryKeywords: ['salary hike India', 'hike negotiation script', 'appraisal negotiation', 'asking for raise India'],
    longTailKeywords: ['how to ask for salary hike in India', 'how much hike to ask at appraisal', 'salary hike negotiation script India', 'how to negotiate hike with manager', 'average hike in India 2026', 'how to ask for 30 percent hike'],
    faqs: [
      { q: 'How much hike?', a: '15 to 22 percent for strong performers. 30 percent only with title or scope change.' },
      { q: 'Average hike in India 2026?', a: '9.5 percent weighted. Top performers 14 to 18 percent.' },
      { q: 'When should I ask?', a: '4 to 8 weeks before appraisal freeze.' },
      { q: 'What if budget capped?', a: 'Separate cash from total package. RSUs, one-time bonus, title change can close 30-50 percent of gap.' },
    ],
  },
  'latex-resume-templates': {
    slug: 'latex-resume-templates',
    title: 'LaTeX Resume Templates for Engineers on Overleaf (2026)',
    description: '7 battle-tested Overleaf LaTeX templates ranked by use case, a copy-paste starter file, the 5-minute Overleaf setup, and 6 layout pitfalls.',
    category: 'AI Resume Tools',
    categorySlug: 'ai-resume',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
    publishAt: '2026-08-13T05:48:00Z',
    primaryKeyword: 'LaTeX resume template',
    secondaryKeywords: ['Overleaf resume', 'LaTeX CV', 'engineering resume LaTeX', 'Deedy resume LaTeX'],
    longTailKeywords: ['best LaTeX resume template', 'Overleaf LaTeX resume', 'Deedy resume template', 'one page LaTeX resume', 'LaTeX resume for software engineer', 'LaTeX CV for PhD'],
    faqs: [
      { q: 'Is LaTeX worth it for a resume?', a: 'Yes if you know it. For one-off, Word / Docs faster.' },
      { q: 'Is Deedy still good?', a: 'For human-read + campus, yes. For ATS, no (2-column parses scrambled).' },
      { q: 'pdfLaTeX vs XeLaTeX?', a: 'pdfLaTeX faster and more ATS-friendly.' },
      { q: 'How to keep to one page?', a: 'Margin 0.6in, itemsep 1pt, body 10.5pt.' },
    ],
  },
  'linkedin-about-section': {
    slug: 'linkedin-about-section',
    title: 'LinkedIn About Section: The Full Template (2026)',
    description: 'A 5-beat formula (Hook, Proof, Angle, Looking for, CTA), 6 worked examples from fresher to executive, and the 7 mistakes that make your About invisible to recruiter search.',
    category: 'LinkedIn & Personal Brand',
    categorySlug: 'linkedin-brand',
    datePublished: '2026-08-16',
    dateModified: '2026-08-16',
    publishAt: '2026-08-16T05:24:00Z',
    primaryKeyword: 'LinkedIn About section',
    secondaryKeywords: ['LinkedIn About me', 'LinkedIn profile About', 'LinkedIn summary template', 'About section LinkedIn'],
    longTailKeywords: ['LinkedIn About section examples', 'LinkedIn About me template', 'LinkedIn About section for freshers', 'LinkedIn About section for software engineer', 'how to write LinkedIn About section', 'LinkedIn About section best practices'],
    faqs: [
      { q: 'First person or third?', a: 'First person. Third reads corporate and less trusted.' },
      { q: 'How long?', a: '1,200 to 1,800 characters. First 300 are mobile fold and matter most.' },
      { q: 'Is it important?', a: 'Yes. Indexed by recruiter search, read carefully by hiring managers.' },
      { q: 'How often to update?', a: 'Every 6 months minimum. After job change or major win.' },
    ],
  },
};

export function getBlogSeo(slug: string): BlogSeo | undefined {
  return BLOG_SEO[slug];
}
